name: 🎉 Build & Deploy Next.js Static to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🚀 Build App & Sync via SFTP/SSH
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-style: 'npm'
        node-version: 20 
        cache: 'npm'

    - name: 📦 Install Dependencies
      run: npm ci

    - name: 🏗️ Build Next.js Export
      run: npm run build

    - name: 📂 Sync "out" Folder to Hostinger via rsync
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        REMOTE_HOST: ${{ secrets.FTP_SERVER }}    
        REMOTE_USER: ${{ secrets.FTP_USERNAME }} 
        REMOTE_PORT: 65002                        
        PASSWORD: ${{ secrets.FTP_PASSWORD }}      
        SOURCE: "out/"
        TARGET: "/home/u424643544/domains/rakitdigital.com/public_html/" 
        ARGS: "-rlgoDIVz --delete"